# Generated by Django 3.2.6 on 2022-09-30 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlPanel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='timer',
            field=models.FloatField(default=8),
            preserve_default=False,
        ),
    ]
