# Generated by Django 3.2.6 on 2022-10-03 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlPanel', '0004_alter_server_timer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='timer',
            field=models.FloatField(),
        ),
    ]
