# Generated by Django 3.2.6 on 2022-10-03 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controlPanel', '0005_alter_server_timer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='timer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controlPanel.timer'),
        ),
    ]
