# Generated by Django 3.2.6 on 2022-10-04 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlPanel', '0008_remove_server_timer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timer',
            name='timer',
            field=models.CharField(max_length=10),
        ),
    ]
