# Generated by Django 3.2.6 on 2022-10-04 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlPanel', '0009_alter_timer_timer'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='domanda',
            field=models.TextField(default='ciao'),
        ),
        migrations.AddField(
            model_name='server',
            name='risposta',
            field=models.TextField(default='ciao benvenuto sono qui per chiarire i tuoi dubbi a proposito del superbonus         come ottenerlo le verifiche preliminari i destinatari i salti         di classe energetica gli interventi possibili i problemi di agibilità         pre e post operam'),
        ),
    ]
