# Generated by Django 3.2.6 on 2022-10-04 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlPanel', '0011_alter_server_risposta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='risposta',
            field=models.TextField(default='AIKA2 server response = {"risposta": "ciao benvenuto il mio compito è di rispondere alle tue domande a proposito del superbonus come ottenerlo le verifiche preliminari i destinatari i salti di classe energetica gli interventi possibili i problemi di agibilità pre e post operam", "question": "ciao", "data": "[{"action_list": [], "action_response": "ciao benvenuto il mio compito è di rispondere alle tue domande a proposito del superbonus come ottenerlo le verifiche preliminari i destinatari i salti di classe energetica gli interventi possibili i problemi di agibilità pre e post operam", "input_str": "ciao", "input_list": ["ciao"], "last_subclass": "saluto", "last_class": "root", "class_context": "", "user_key": "CAMCOM"}]", "sentiment": "0", "dialog": "start"} ciao benvenuto sono qui per chiarire i tuoi dubbi a proposito del superbonus come ottenerlo le verifiche preliminari i destinatari i salti di classe energetica gli interventi possibili i problemi di agibilità pre e post operam'),
        ),
    ]
