# Generated by Django 3.2.6 on 2022-10-05 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlPanel', '0013_alter_server_risposta'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='tipoRisposta',
            field=models.TextField(default='dizionario'),
        ),
    ]
