# Generated by Django 3.2.6 on 2022-10-05 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlPanel', '0014_server_tiporisposta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='risposta',
            field=models.TextField(default='\n    ciao benvenuto sono disponibile per darti informazioni riguardo al superbonus come ottenerlo le verifiche preliminari i destinatari i salti di classe energetica gli interventi possibili i problemi di agibilità pre e post operam#\n    ciao benvenuto sono qui per chiarire i tuoi dubbi a proposito del superbonus come ottenerlo le verifiche preliminari i destinatari i salti di classe energetica gli interventi possibili i problemi di agibilità pre e post operam#\n    ciao benvenuto il mio compito è di rispondere alle tue domande a proposito del superbonus come ottenerlo le verifiche preliminari i destinatari i salti di classe energetica gli interventi possibili i problemi di agibilità pre e post operam'),
        ),
    ]
