# Generated by Django 3.2.6 on 2022-10-12 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlPanel', '0017_auto_20221012_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='tipoRisposta',
            field=models.TextField(),
        ),
    ]
