# Generated by Django 3.2.6 on 2022-10-12 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlPanel', '0019_alter_server_risposta'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimerInMinuti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timer', models.CharField(max_length=10)),
            ],
        ),
    ]
