# Generated by Django 3.2.6 on 2022-10-12 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlPanel', '0020_timerinminuti'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimerInMinuti',
        ),
        migrations.AddField(
            model_name='timer',
            name='timerInMinuti',
            field=models.CharField(default=60, max_length=10),
        ),
    ]
