# Generated by Django 3.2.6 on 2022-10-12 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlPanel', '0021_auto_20221012_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timer',
            name='timerInMinuti',
            field=models.CharField(max_length=10),
        ),
    ]
