# Generated by Django 3.2.6 on 2022-10-12 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controlPanel', '0022_alter_timer_timerinminuti'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timer',
            name='timerInMinuti',
        ),
    ]
