# Generated by Django 5.0 on 2024-01-14 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlPanel', '0023_remove_timer_timerinminuti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timer',
            name='timer',
            field=models.IntegerField(),
        ),
    ]
