# Generated by Django 5.0 on 2024-01-14 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlPanel', '0024_alter_timer_timer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timer',
            name='timer',
            field=models.CharField(max_length=10),
        ),
    ]
